import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sample for Next.js and Editor.js
        </h1>

        <div className={styles.grid}>
          <Link href='/blog/create'>
            <div className={styles.card}>
              <h2>Create Blog &rarr;</h2>
              <p>Open Editor js instance to start creating your blog</p>
            </div>
          </Link>

          <Link href='/blog/learn-next-and-editor-js'>
            <div className={styles.card}>
              <h2>Sample Blog &rarr;</h2>
              <p>View a sample server side rendered blog made with editor js</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
